/*
 * This file is generated by jOOQ.
 */
package example.generate.code.model.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDate;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "user",
    schema = "public",
    uniqueConstraints = {
        @UniqueConstraint(name = "user_pkey", columnNames = { "id" })
    }
)
public interface IUser extends Serializable {

    /**
     * Setter for <code>public.user.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>public.user.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, precision = 64)
    public Long getId();

    /**
     * Setter for <code>public.user.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>public.user.name</code>.
     */
    @Column(name = "name")
    public String getName();

    /**
     * Setter for <code>public.user.age</code>.
     */
    public void setAge(Integer value);

    /**
     * Getter for <code>public.user.age</code>.
     */
    @Column(name = "age", precision = 32)
    public Integer getAge();

    /**
     * Setter for <code>public.user.gender</code>.
     */
    public void setGender(String value);

    /**
     * Getter for <code>public.user.gender</code>.
     */
    @Column(name = "gender")
    public String getGender();

    /**
     * Setter for <code>public.user.birthday</code>.
     */
    public void setBirthday(LocalDate value);

    /**
     * Getter for <code>public.user.birthday</code>.
     */
    @Column(name = "birthday")
    public LocalDate getBirthday();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IUser
     */
    public void from(IUser from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IUser
     */
    public <E extends IUser> E into(E into);
}
