/*
 * This file is generated by jOOQ.
 */
package example.generate.code.model.tables.records;


import example.generate.code.model.tables.User;
import example.generate.code.model.tables.interfaces.IUser;

import java.time.LocalDate;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "user",
    schema = "public",
    uniqueConstraints = {
        @UniqueConstraint(name = "user_pkey", columnNames = { "id" })
    }
)
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record5<Long, String, Integer, String, LocalDate>, IUser {

    private static final long serialVersionUID = -764144249;

    /**
     * Setter for <code>public.user.id</code>.
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, precision = 64)
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.user.name</code>.
     */
    @Override
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user.name</code>.
     */
    @Column(name = "name")
    @Override
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.user.age</code>.
     */
    @Override
    public void setAge(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user.age</code>.
     */
    @Column(name = "age", precision = 32)
    @Override
    public Integer getAge() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.user.gender</code>.
     */
    @Override
    public void setGender(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.user.gender</code>.
     */
    @Column(name = "gender")
    @Override
    public String getGender() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.user.birthday</code>.
     */
    @Override
    public void setBirthday(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.user.birthday</code>.
     */
    @Column(name = "birthday")
    @Override
    public LocalDate getBirthday() {
        return (LocalDate) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, Integer, String, LocalDate> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, String, Integer, String, LocalDate> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return User.USER.ID;
    }

    @Override
    public Field<String> field2() {
        return User.USER.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return User.USER.AGE;
    }

    @Override
    public Field<String> field4() {
        return User.USER.GENDER;
    }

    @Override
    public Field<LocalDate> field5() {
        return User.USER.BIRTHDAY;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getAge();
    }

    @Override
    public String component4() {
        return getGender();
    }

    @Override
    public LocalDate component5() {
        return getBirthday();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getAge();
    }

    @Override
    public String value4() {
        return getGender();
    }

    @Override
    public LocalDate value5() {
        return getBirthday();
    }

    @Override
    public UserRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UserRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public UserRecord value3(Integer value) {
        setAge(value);
        return this;
    }

    @Override
    public UserRecord value4(String value) {
        setGender(value);
        return this;
    }

    @Override
    public UserRecord value5(LocalDate value) {
        setBirthday(value);
        return this;
    }

    @Override
    public UserRecord values(Long value1, String value2, Integer value3, String value4, LocalDate value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IUser from) {
        setId(from.getId());
        setName(from.getName());
        setAge(from.getAge());
        setGender(from.getGender());
        setBirthday(from.getBirthday());
    }

    @Override
    public <E extends IUser> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Long id, String name, Integer age, String gender, LocalDate birthday) {
        super(User.USER);

        setId(id);
        setName(name);
        setAge(age);
        setGender(gender);
        setBirthday(birthday);
    }
}
