server:
  port: 8228
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: generate-code
  datasource:
    url: jdbc:mariadb://localhost:3306/tabuyos?useUnicode=true&characterEncoding=utf8
    username: tabuyos
    password: tabuyos
    initialization-mode: always
    sql-script-encoding: utf-8
