/*
 * This file is generated by jOOQ.
 */
package com.tabuyos.jooq.examples.generate.code.model.tables.pojos;


import com.tabuyos.jooq.examples.generate.code.model.tables.interfaces.IUser;

import java.time.LocalDateTime;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "user",
    schema = "tabuyos",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_user_PRIMARY", columnNames = { "id" })
    }
)
public class User implements IUser {

    private static final long serialVersionUID = -298439854;

    private Integer       id;
    private String        name;
    private Integer       age;
    private Integer       gender;
    private LocalDateTime birthday;

    public User() {}

    public User(IUser value) {
        this.id = value.getId();
        this.name = value.getName();
        this.age = value.getAge();
        this.gender = value.getGender();
        this.birthday = value.getBirthday();
    }

    public User(
        Integer       id,
        String        name,
        Integer       age,
        Integer       gender,
        LocalDateTime birthday
    ) {
        this.id = id;
        this.name = name;
        this.age = age;
        this.gender = gender;
        this.birthday = birthday;
    }

    /**
     * Getter for <code>tabuyos.user.id</code>. user id
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, precision = 10)
    @Override
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>tabuyos.user.id</code>. user id
     */
    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>tabuyos.user.name</code>. user name
     */
    @Column(name = "name", nullable = false, length = 20)
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>tabuyos.user.name</code>. user name
     */
    @Override
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>tabuyos.user.age</code>. user age
     */
    @Column(name = "age", precision = 10)
    @Override
    public Integer getAge() {
        return this.age;
    }

    /**
     * Setter for <code>tabuyos.user.age</code>. user age
     */
    @Override
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * Getter for <code>tabuyos.user.gender</code>. user gender
     */
    @Column(name = "gender", precision = 10)
    @Override
    public Integer getGender() {
        return this.gender;
    }

    /**
     * Setter for <code>tabuyos.user.gender</code>. user gender
     */
    @Override
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * Getter for <code>tabuyos.user.birthday</code>.
     */
    @Column(name = "birthday", nullable = false)
    @Override
    public LocalDateTime getBirthday() {
        return this.birthday;
    }

    /**
     * Setter for <code>tabuyos.user.birthday</code>.
     */
    @Override
    public void setBirthday(LocalDateTime birthday) {
        this.birthday = birthday;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(age);
        sb.append(", ").append(gender);
        sb.append(", ").append(birthday);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IUser from) {
        setId(from.getId());
        setName(from.getName());
        setAge(from.getAge());
        setGender(from.getGender());
        setBirthday(from.getBirthday());
    }

    @Override
    public <E extends IUser> E into(E into) {
        into.from(this);
        return into;
    }
}
