/*
 * This file is generated by jOOQ.
 */
package com.tabuyos.jooq.examples.generate.code.model.tables.daos;


import com.tabuyos.jooq.examples.generate.code.model.tables.Depart;
import com.tabuyos.jooq.examples.generate.code.model.tables.records.DepartRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class DepartDao extends DAOImpl<DepartRecord, com.tabuyos.jooq.examples.generate.code.model.tables.pojos.Depart, Integer> {

    /**
     * Create a new DepartDao without any configuration
     */
    public DepartDao() {
        super(Depart.DEPART, com.tabuyos.jooq.examples.generate.code.model.tables.pojos.Depart.class);
    }

    /**
     * Create a new DepartDao with an attached configuration
     */
    @Autowired
    public DepartDao(Configuration configuration) {
        super(Depart.DEPART, com.tabuyos.jooq.examples.generate.code.model.tables.pojos.Depart.class, configuration);
    }

    @Override
    public Integer getId(com.tabuyos.jooq.examples.generate.code.model.tables.pojos.Depart object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.tabuyos.jooq.examples.generate.code.model.tables.pojos.Depart> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Depart.DEPART.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.tabuyos.jooq.examples.generate.code.model.tables.pojos.Depart> fetchById(Integer... values) {
        return fetch(Depart.DEPART.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.tabuyos.jooq.examples.generate.code.model.tables.pojos.Depart fetchOneById(Integer value) {
        return fetchOne(Depart.DEPART.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.tabuyos.jooq.examples.generate.code.model.tables.pojos.Depart> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Depart.DEPART.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.tabuyos.jooq.examples.generate.code.model.tables.pojos.Depart> fetchByName(String... values) {
        return fetch(Depart.DEPART.NAME, values);
    }

    /**
     * Fetch records that have <code>age BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.tabuyos.jooq.examples.generate.code.model.tables.pojos.Depart> fetchRangeOfAge(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Depart.DEPART.AGE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>age IN (values)</code>
     */
    public List<com.tabuyos.jooq.examples.generate.code.model.tables.pojos.Depart> fetchByAge(Integer... values) {
        return fetch(Depart.DEPART.AGE, values);
    }

    /**
     * Fetch records that have <code>local BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.tabuyos.jooq.examples.generate.code.model.tables.pojos.Depart> fetchRangeOfLocal(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Depart.DEPART.LOCAL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>local IN (values)</code>
     */
    public List<com.tabuyos.jooq.examples.generate.code.model.tables.pojos.Depart> fetchByLocal(Integer... values) {
        return fetch(Depart.DEPART.LOCAL, values);
    }

    /**
     * Fetch records that have <code>create_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.tabuyos.jooq.examples.generate.code.model.tables.pojos.Depart> fetchRangeOfCreateTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Depart.DEPART.CREATE_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.tabuyos.jooq.examples.generate.code.model.tables.pojos.Depart> fetchByCreateTime(LocalDateTime... values) {
        return fetch(Depart.DEPART.CREATE_TIME, values);
    }
}
