/*
 * This file is generated by jOOQ.
 */
package com.tabuyos.jooq.examples.generate.code.model;


import com.tabuyos.jooq.examples.generate.code.model.tables.Depart;
import com.tabuyos.jooq.examples.generate.code.model.tables.User;


/**
 * Convenience access to all tables in tabuyos.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>tabuyos.depart</code>.
     */
    public static final Depart DEPART = Depart.DEPART;

    /**
     * The table <code>tabuyos.user</code>.
     */
    public static final User USER = User.USER;
}
