/*
 * This file is generated by jOOQ.
 */
package com.tabuyos.jooq.examples.generate.code.model;


import com.tabuyos.jooq.examples.generate.code.model.tables.Depart;
import com.tabuyos.jooq.examples.generate.code.model.tables.User;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tabuyos extends SchemaImpl {

    private static final long serialVersionUID = -1438940212;

    /**
     * The reference instance of <code>tabuyos</code>
     */
    public static final Tabuyos TABUYOS = new Tabuyos();

    /**
     * The table <code>tabuyos.depart</code>.
     */
    public final Depart DEPART = Depart.DEPART;

    /**
     * The table <code>tabuyos.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Tabuyos() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Depart.DEPART,
            User.USER);
    }
}
