/*
 * This file is generated by jOOQ.
 */
package com.tabuyos.jooq.examples.generate.code.model.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "user",
    schema = "tabuyos",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_user_PRIMARY", columnNames = { "id" })
    }
)
public interface IUser extends Serializable {

    /**
     * Setter for <code>tabuyos.user.id</code>. user id
     */
    public void setId(Integer value);

    /**
     * Getter for <code>tabuyos.user.id</code>. user id
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, precision = 10)
    public Integer getId();

    /**
     * Setter for <code>tabuyos.user.name</code>. user name
     */
    public void setName(String value);

    /**
     * Getter for <code>tabuyos.user.name</code>. user name
     */
    @Column(name = "name", nullable = false, length = 20)
    public String getName();

    /**
     * Setter for <code>tabuyos.user.age</code>. user age
     */
    public void setAge(Integer value);

    /**
     * Getter for <code>tabuyos.user.age</code>. user age
     */
    @Column(name = "age", precision = 10)
    public Integer getAge();

    /**
     * Setter for <code>tabuyos.user.gender</code>. user gender
     */
    public void setGender(Integer value);

    /**
     * Getter for <code>tabuyos.user.gender</code>. user gender
     */
    @Column(name = "gender", precision = 10)
    public Integer getGender();

    /**
     * Setter for <code>tabuyos.user.birthday</code>.
     */
    public void setBirthday(LocalDateTime value);

    /**
     * Getter for <code>tabuyos.user.birthday</code>.
     */
    @Column(name = "birthday", nullable = false)
    public LocalDateTime getBirthday();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IUser
     */
    public void from(IUser from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IUser
     */
    public <E extends IUser> E into(E into);
}
